server:
  port: 8081

spring:
  application:
    name: user-service


  datasource:
    url:  url: jdbc:mysql://user-mysql:3309/auth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka